## What is numpy?
Numpy is a powerful library used for numerical operation in Python.
1. Efficient in numerical computations compare with python list
2. Array(matrix) manipulation

In [28]:
##import numpy
import numpy as np

## create a numpy array

## a 1D array
array1 = np.array([1, 2, 3, 4, 5])

## a 2D array
array2 = np.array([[1, 2, 3], [4, 5, 6]])

## a 3D array
array3 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

## a 4D array
array4 = np.array([[[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]], [[[13, 14, 15], [16, 17, 18]], [[19, 20, 21], [22, 23, 24]]]])

print(array1, "\n\n" ,array2, "\n\n", array3, "\n\n", array4)

[1 2 3 4 5] 

 [[1 2 3]
 [4 5 6]] 

 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]] 

 [[[[ 1  2  3]
   [ 4  5  6]]

  [[ 7  8  9]
   [10 11 12]]]


 [[[13 14 15]
   [16 17 18]]

  [[19 20 21]
   [22 23 24]]]]


In [31]:
## Check the shape of the array
print(array3.shape)
## The result will be (2, 2, 3) which means that the array has 2 elements, each element has 2 elements, and each of those elements has 3 elements.

## Check the size of the array
print(array3.size)
## The result will be 12 which means that the array has 12 elements.

## Check the dimension of the array
print(array3.ndim)
## The result will be 3 which means that the array has 3 dimensions.
## This means (depth, rows, columns), in total 3 dimensions.



(2, 2, 3)
12
3


In [42]:
## Create an array with zeros
array5 = np.zeros((2, 3)) ## 2 rows, 3 columns
print(array5, "\n")

## Create an array with ones
array6 = np.ones((2, 3)) ## 2 rows, 3 columns
print(array6, "\n")

## Create an array with random numbers
array7 = np.random.random((2, 3)) ## 2 rows, 3 columns ## random numbers between 0 and 1
print(array7, "\n")


[[0. 0. 0.]
 [0. 0. 0.]] 

[[1. 1. 1.]
 [1. 1. 1.]] 

[[0.10144851 0.85760776 0.74501719]
 [0.95871944 0.42411759 0.6500538 ]] 



In [46]:
## Create an array with a range of numbers
array8 = np.arange(1, 10, 2) ## start, stop, step
print(array8, "\n")

## Create an array with evenly spaced numbers
array9 = np.linspace(1, 10, 6) ## start, stop, number of elements
print(array9, "\n")

[1 3 5 7 9] 

[ 1.   2.8  4.6  6.4  8.2 10. ] 

