In [1]:
import numpy as np

In [3]:
## Basic operation
arr = np.array([1, 2, 3, 4, 5])

## element-wise operation
arr = arr + 1
print(arr)

arr = arr - 1
print(arr)

arr = arr * 2 
print(arr)

arr = arr / 2
print(arr)

[2 3 4 5 6]
[1 2 3 4 5]
[ 2  4  6  8 10]
[1. 2. 3. 4. 5.]


In [9]:
## matrix operation

array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

print(array1 + array2)
print(array1 - array2)
print(array1 * array2) ## this is element-wise multiplication
print(array1 @ array2) ## this is matrix multiplication
print(np.dot(array1, array2)) ## this is matrix multiplication

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [14]:
## Array indexing and slicing

arr = np.array([1, 2, 3, 4, 5])

## Access specific element
print(arr[0])
print(arr[1])

## Slice array
print(arr[1:3]) ## 3 is exclusive
print(arr[:3])
print(arr[3:])

## Modify element
arr[2] = 10
print(arr)


1
2
[2 3]
[1 2 3]
[4 5]
[ 1  2 10  4  5]


In [25]:
## Slicing 2D array
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(matrix[0, 0]) ## 0 row, 0 column
print(matrix[0, :]) ## first row, all columns
print(matrix[:, 0]) ## all rows, first column
print(matrix[0:2, 0:2]) ## first 2 rows, first 2 columns, this is a sub-matrix 

1
[1 2 3]
[1 4 7]
[[1 2]
 [4 5]]
