In [2]:
import numpy as np

## Mean
$mean = \frac{1}{N} \sum (x_i)$

## Std
$\text{std} = \sqrt{\frac{1}{N} \sum_{i=1}^{N} (x_i - \mu)^2}$

In [21]:
array1 = np.array([1,2,3,4,5])
array2 = np.array([[[16,17,18,19,20], [21,22,23,24,25]], [[26,27,28,29,30], [31,32,33,34,35]]])

## sum, mean, max, min operation, useful for statistics and data analysis
print(np.sum(array1)) ## sum up all elements in the array
print(np.mean(array1)) ## calculate the mean of the array
print(np.max(array1))
print(np.min(array1))

## sum, mean, max, min operation along specific axis
print("\n",np.sum(array2, axis=0)) ## sum up all elemements along axis 0 (two 2x5 arrays)
print(np.sum(array2, axis=1)) ## sum up all elemements along axis 1 (two 2x5 arrays)
print(np.sum(array2, axis=2)) ## sum up all elemements along axis 2 (two 2x2 arrays)

## standard deviation and variance
print(np.std(array1))
print(np.var(array1))

## standard deviation and variance along specific axis
print("\n\n",np.std(array2, axis=0))
print(np.std(array2, axis=1))

## index of max and min
print(np.argmax(array1))
print(np.argmin(array1))

15
3.0
5
1

 [[42 44 46 48 50]
 [52 54 56 58 60]]
[[37 39 41 43 45]
 [57 59 61 63 65]]
[[ 90 115]
 [140 165]]
1.4142135623730951
2.0


 [[5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]]
[[2.5 2.5 2.5 2.5 2.5]
 [2.5 2.5 2.5 2.5 2.5]]
4
0
