In [1]:
import numpy as np

In [8]:
array1 = np.array([1, 2, 3, 4, 5, 6])

## reshape array1 to 2D array
array2 = array1.reshape(2, 3)
print(array2)

## flatten array2 to 1D array
array3 = array2.flatten()
print(array3)

## transpose array2
array4 = np.transpose(array2)
array4 = array2.T
print(array4)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
[[1 4]
 [2 5]
 [3 6]]
