In [ ]:
import numpy as np

## Numpy broadcasting rules:
# 1. If the two arrays differ in their number of dimensions, the shape of the one with fewer dimensions is padded with ones on its leading (left) side.
# 2. If the shape of the two arrays does not match in any dimension, the array with shape equal to 1 in that dimension is stretched to match the other shape.

# Broadcasting example 1
a = np.array([0, 1, 2])
b = np.array([1])

## b will be broadcasted to [1 1 1]
print(a + b) # [1 2 3]

# Broadcasting example 2
a = np.array([0, 1, 2, 3])
b = np.array([1, 2])

## b can not be broadcasted, because the number of dimensions is neither equal nor one of them is 1


# Broadcasting example 3
a = np.array([[0], [1], [2]])
b = np.array([1, 2])

## a will be broadcasted to [[0 0], [1 1], [2 2]]
## b will be broadcasted to [[1 2], [1 2], [1 2]]

print(a + b) # [[1 2], [2 3], [3 4]]

## Broadcasting example 4
a = np.array([[0, 1, 2, 9], [3, 4, 5, 10], [6, 7, 8, 11]]) ## 3x4
b = np.array([[0, 1, 2, 9], [3, 4, 5, 10], [6, 7, 8, 11], [12, 13, 14, 15]]) ## 4x4

## a and b can not be broadcasted, because the number of dimensions is neither equal nor one of them is 1
## We have two ways to solve the problem
## 1. slice b array into 3x4

b_slice = b[:3, :]
print(a + b_slice)

## 2. Add new axis to make shapes broadcast-compatible
a_exp = a[:, :, np.newaxis] ## 3x4x1
b_exp = b[np.newaxis, :, :] ## 1x4x4

print(a_exp + b_exp) ## 3x4x4



[1 2 3]
[[1 2]
 [2 3]
 [3 4]]
[[ 0  2  4 18]
 [ 6  8 10 20]
 [12 14 16 22]]
[[[ 0  1  2  9]
  [ 4  5  6 11]
  [ 8  9 10 13]
  [21 22 23 24]]

 [[ 3  4  5 12]
  [ 7  8  9 14]
  [11 12 13 16]
  [22 23 24 25]]

 [[ 6  7  8 15]
  [10 11 12 17]
  [14 15 16 19]
  [23 24 25 26]]]


In [18]:
arr = np.array([[[1, 2],
                 [3, 4]],
                [[5, 6],
                 [7, 8]]])  # shape: (2,2,2)

## sum depth wise, two matrices will be summed
print(np.sum(arr, axis=0))  # shape: (2,2)

## sum column values
print(np.sum(arr, axis=1))  # shape: (2,2)

## sum row values
print(np.sum(arr, axis=2))  # shape: (2,2)



[[ 6  8]
 [10 12]]
[[ 4  6]
 [12 14]]
[[ 3  7]
 [11 15]]
