## Linear Algebra Operation


In [1]:
import numpy as np 

## Matrix Operation

For dot product
```bash
np.dot
```
or
```bash
A @ B
```

In [4]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[7, 8, 9], [10, 11, 12]])

a = a.T
print (a)

c = np.dot(a, b)
print(c)

d = a @ b
print(d)


[[1 4]
 [2 5]
 [3 6]]
[[47 52 57]
 [64 71 78]
 [81 90 99]]
[[47 52 57]
 [64 71 78]
 [81 90 99]]


## Statistical Operation
### Mean
$mean = \frac{1}{N} \sum (x_i)$

### Std
$\text{std} = \sqrt{\frac{1}{N} \sum_{i=1}^{N} (x_i - \mu)^2}$

### var
Variance measures the average squared deviation from the mean, representing data spread.
$\text{var} = \sigma^2 = \frac{1}{N} \sum_{i=1}^{N} (x_i - \mu)^2$
#### Sample Variance
$s^2 = \frac{1}{N-1} \sum_{i=1}^{N} (x_i - \bar{x})^2$

### Covariance
Covariance measures the linear relationship between two variables, indicating how they vary together.
$\text{Cov}(X,Y) = \sigma_{XY} = \frac{1}{N} \sum_{i=1}^{N} (x_i - \mu_X)(y_i - \mu_Y)$

#### Sample Covariance
$\text{Cov}(X,Y) = \frac{1}{N-1} \sum_{i=1}^{N} (x_i - \bar{x})(y_i - \bar{y})$

Pearson Correlation Coefficient
### Correlation
Correlation measures the strength and direction of linear relationship between two variables, normalized to [-1, 1].
$r_{XY} = \rho_{XY} = \frac{\text{Cov}(X,Y)}{\sigma_X \sigma_Y} = \frac{\sum_{i=1}^{N} (x_i - \bar{x})(y_i - \bar{y})}{\sqrt{\sum_{i=1}^{N} (x_i - \bar{x})^2} \sqrt{\sum_{i=1}^{N} (y_i - \bar{y})^2}}$

In [8]:
array1 = np.array([1,2,3,4,5])
array2 = np.array([[[16,17,18,19,20], [21,22,23,24,25]], [[26,27,28,29,30], [31,32,33,34,35]]])

# Calculate the mean of array2 along axis 0
mean = np.mean(array2, axis=0)
print(mean)

# Calculate the mean of array2 along columns
mean = np.mean(array2, axis=1)
print(mean)

# Std
std = np.std(array2, axis=0)
print(std)


[[21. 22. 23. 24. 25.]
 [26. 27. 28. 29. 30.]]
[[18.5 19.5 20.5 21.5 22.5]
 [28.5 29.5 30.5 31.5 32.5]]
[[5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]]


In [25]:
array = np.random.rand(64)
array = array.reshape(8, 8)

## Covariance
covariance = np.cov(array, rowvar=False)
print(covariance)

## Variance
variance = np.var(array, axis=0)
print(variance)

# Correlation
correlation = np.corrcoef(array, rowvar=False)
print(correlation)

[[ 0.0233211   0.00346776 -0.00356825 -0.02819217  0.00753168 -0.01047079
  -0.03171375  0.01119889]
 [ 0.00346776  0.09481331  0.03460011 -0.00890473 -0.03191958  0.01694337
   0.01686897  0.00128785]
 [-0.00356825  0.03460011  0.0324755   0.02740996  0.01314264 -0.01130081
   0.01489747 -0.00494342]
 [-0.02819217 -0.00890473  0.02740996  0.12666734  0.04147881  0.03008797
  -0.01063489 -0.01782648]
 [ 0.00753168 -0.03191958  0.01314264  0.04147881  0.11752735 -0.01122218
  -0.02852987  0.02399891]
 [-0.01047079  0.01694337 -0.01130081  0.03008797 -0.01122218  0.07126838
  -0.02370109 -0.0024831 ]
 [-0.03171375  0.01686897  0.01489747 -0.01063489 -0.02852987 -0.02370109
   0.09847656 -0.0067699 ]
 [ 0.01119889  0.00128785 -0.00494342 -0.01782648  0.02399891 -0.0024831
  -0.0067699   0.03230378]]
[0.02040596 0.08296165 0.02841607 0.11083393 0.10283643 0.06235984
 0.08616699 0.02826581]
[[ 1.          0.07374615 -0.12965903 -0.51870658  0.14386265 -0.25683638
  -0.6617695   0.40801299]


## Linear Algebra functions

we can use functions:
```bash
np.linalg
```

In [26]:
array = np.random.rand(64)
array = array.reshape(8, 8)

## eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(array)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)

## SVD
u, sigma, vh = np.linalg.svd(array)
print("U:\n", u)
print("Sigma:\n", sigma)
print("Vh:\n", vh)

## QR decomposition
q, r = np.linalg.qr(array)
print("Q:\n", q)
print("R:\n", r)

## Matrix inverse
try:
    inverse = np.linalg.inv(array)
    print("Inverse:\n", inverse)
except np.linalg.LinAlgError as e:
    print("Matrix is singular, cannot compute inverse:", e)
    
## Matrix determinant
try:
    determinant = np.linalg.det(array)
    print("Determinant:", determinant)
except np.linalg.LinAlgError as e:
    print("Matrix is singular, cannot compute determinant:", e)
    
## Matrix rank
rank = np.linalg.matrix_rank(array)
print("Rank:", rank)

## Matrix norm
norm_for = np.linalg.norm(array, ord='fro')  # Frobenius norm
print("Norm:", norm_for)

norm_2 = np.linalg.norm(array, ord=2)  # 2-norm (spectral norm)
print("2-Norm:", norm_2)

## Matrix trace
trace = np.trace(array)
print("Trace:", trace)

Eigenvalues: [ 4.11885594+0.j          0.59785841+0.4383783j   0.59785841-0.4383783j
 -0.73915488+0.18473459j -0.73915488-0.18473459j -0.16963374+0.17926778j
 -0.16963374-0.17926778j  0.19327626+0.j        ]
Eigenvectors:
 [[-0.46242386+0.j          0.51063272+0.j          0.51063272-0.j
  -0.10253218-0.10338338j -0.10253218+0.10338338j  0.11921357-0.11062585j
   0.11921357+0.11062585j  0.12946384+0.j        ]
 [-0.36830267+0.j         -0.09143175-0.34326972j -0.09143175+0.34326972j
   0.54231133+0.j          0.54231133-0.j          0.20104374-0.10116187j
   0.20104374+0.10116187j -0.08179563+0.j        ]
 [-0.25089545+0.j          0.11865713+0.32383798j  0.11865713-0.32383798j
  -0.24303165+0.18795468j -0.24303165-0.18795468j -0.29490544+0.10597298j
  -0.29490544-0.10597298j -0.56512015+0.j        ]
 [-0.33805386+0.j          0.0508903 +0.23113716j  0.0508903 -0.23113716j
   0.28785263+0.20020284j  0.28785263-0.20020284j -0.02276298+0.05113485j
  -0.02276298-0.05113485j  0.27167047+0.