## What is numpy?
Numpy is a powerful library used for numerical operation in Python.
1. Efficient in numerical computations compare with python list
2. Array(matrix) manipulation

### Basic array creation
Using np.array function

In [2]:
import numpy as np

In [3]:
## 1D array
array_1d = np.array([1, 2, 3, 4, 5])

## 2D array
array_2d = np.array([[1, 2, 3], [4, 5, 6]])

## transpose of a 2D array
array_2d_transpose = array_2d.T

print("1D Array:\n", array_1d)
print("2D Array:\n", array_2d)
print("Transposed 2D Array:\n", array_2d_transpose)

1D Array:
 [1 2 3 4 5]
2D Array:
 [[1 2 3]
 [4 5 6]]
Transposed 2D Array:
 [[1 4]
 [2 5]
 [3 6]]


In [4]:
## Displaying the shape of the arrays
print("Shape of 2D Array:", array_2d.shape)

print("Size of 2D Array:", array_2d.size)

print("Data type of 2D Array:", array_2d.dtype)

print("Number of dimensions of 2D Array:", array_2d.ndim)

Shape of 2D Array: (2, 3)
Size of 2D Array: 6
Data type of 2D Array: int64
Number of dimensions of 2D Array: 2


## Matrices Creation Functions
### Create all zeros matrix
np.zeros((3,4))

### Create all one matrix
np.ones((3,4))

### Create identity matrix
np.eye(4)

In [5]:
zero_matrix = np.zeros((3, 3))
one_matrix = np.ones((3, 3))
identity_matrix = np.eye(3)

print("Zero Matrix:\n", zero_matrix)
print("One Matrix:\n", one_matrix)
print("Identity Matrix:\n", identity_matrix)

Zero Matrix:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
One Matrix:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## Data type and memory management

We can assign desired data type in the array by using dtype = np.int32, 64.....

In [6]:
int_array = np.array([1, 2, 3], dtype=np.int64)
float_array = np.array([1.0, 2.0, 3.0], dtype=np.float64)

print("Integer Array:", int_array)
print("Float Array:", float_array)

complex_array = np.array([1+2j, 3+4j], dtype=np.complex128)
print("Complex Array:", complex_array)

## We are also able to convert between data types
converted_int_array = float_array.astype(np.int64)
print("Converted Integer Array from Float Array:", converted_int_array)

Integer Array: [1 2 3]
Float Array: [1. 2. 3.]
Complex Array: [1.+2.j 3.+4.j]
Converted Integer Array from Float Array: [1 2 3]


## Indexing and Slicing

This is a very important function of matrix operation.

In [7]:
arr = np.arange(24).reshape(4, 6)
print("2D Array:\n", arr)

# single element access
print("Element at (1, 2):", arr[1, 2])

# slicing
get_row = arr[1, :]  # get the second row
print("Second Row:", get_row)

get_column = arr[:, 2]  # get the third column
print("Third Column:", get_column)

sub_array = arr[1:3, 2:4]  # get a sub-array
print("Sub-array (rows 1-2, columns 2-3):\n", sub_array)

2D Array:
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
Element at (1, 2): 8
Second Row: [ 6  7  8  9 10 11]
Third Column: [ 2  8 14 20]
Sub-array (rows 1-2, columns 2-3):
 [[ 8  9]
 [14 15]]


In [8]:
## Advanced indexing

## Boolean indexing
bool_index = arr > 10  # create a boolean index
print("Boolean Index:\n", bool_index)

bool_filtered = arr[bool_index]  # filter the array using the boolean index
print("Filtered Array (values > 10):", bool_filtered)

# Fancy indexing
fancy_index = arr[[0, 2], [1, 3]]  # get elements at (0,1) and (2,3)
print("Fancy Indexing Result:", fancy_index)

Boolean Index:
 [[False False False False False False]
 [False False False False False  True]
 [ True  True  True  True  True  True]
 [ True  True  True  True  True  True]]
Filtered Array (values > 10): [11 12 13 14 15 16 17 18 19 20 21 22 23]
Fancy Indexing Result: [ 1 15]


## Broadcasting

Broadcasting enables operations between arrays of different shapes without explicit loops.

### Rule of broadcasting:
* 1. If the arrays have different numbers of dimensions, the shape of the smaller-dimensional array is padded with ones on the left side until both shapes are the same length.
* 2. If the shapes of the arrays do not match in any dimension, the array with shape 1 in that dimension is stretched to match the other array's shape.
* 3. If the shapes still do not match, an error is raised.


In [9]:
arr = np.array([[1,2,3], [4,5,6]])
result = arr + 10

row_vector = np.array([10, 20, 30])
column_vector = np.array([[10], [20], [30]])

result_addition = row_vector + column_vector  # broadcasting
print("the result of adding row and column vectors:\n", result_addition)

## In this case, the row vector is 1*3 will be broadcasted to 3*3, and the column vector is 3*1 will be broadcasted to 3*3.

the result of adding row and column vectors:
 [[20 30 40]
 [30 40 50]
 [40 50 60]]


In [10]:
# Broadcasting example 2
a = np.array([0, 1, 2, 3])
b = np.array([1, 2])

# a is shape 1* 4
# b is shape 1* 2
# b can not be broadcasted to the shape of a

## More complex example
If the matrix can not be broadcasted, we can do:
1. slicing one of the matrix.
2. using np.newaxis to add one dimensions into two matrices, then the dim with 1 will be broadcasted.

In [11]:
## Broadcasting example 3
a = np.array([[0, 1, 2, 9], [3, 4, 5, 10], [6, 7, 8, 11]]) ## 3x4
b = np.array([[0, 1, 2, 9], [3, 4, 5, 10], [6, 7, 8, 11], [12, 13, 14, 15]]) ## 4x4

## a and b can not be broadcasted, because the number of dimensions is neither equal nor one of them is 1
## We have two ways to solve the problem

## 1. slice b array into 3x4

b_slice = b[:3, :]
print(a + b_slice)

## 2. Add new axis to make shapes broadcast-compatible
a_exp = a[:, :, np.newaxis] ## 3x4x1
b_exp = b[np.newaxis, :, :] ## 1x4x4

print(a_exp + b_exp) ## 3x4x4


[[ 0  2  4 18]
 [ 6  8 10 20]
 [12 14 16 22]]
[[[ 0  1  2  9]
  [ 4  5  6 11]
  [ 8  9 10 13]
  [21 22 23 24]]

 [[ 3  4  5 12]
  [ 7  8  9 14]
  [11 12 13 16]
  [22 23 24 25]]

 [[ 6  7  8 15]
  [10 11 12 17]
  [14 15 16 19]
  [23 24 25 26]]]


## Study of broadcasting example


In [ ]:
arr = np.array([[[1, 2],
                 [3, 4]],
                [[5, 6],
                 [7, 8]]])  # shape: (2,2,2)

## sum depth wise, two matrices will be summed
print(np.sum(arr, axis=0))  # shape: (2,2)
## This will sume the two 2x2 matrices into one 2x2 matrix

## sum column values
print(np.sum(arr, axis=1))  # shape: (2,2)
## This will the column of individual matrices, building a new 2x2 matrix

## sum row values
print(np.sum(arr, axis=2))  # shape: (2,2)
## This will sum the row of individual matrices, building a new 2x2 matrix


[[ 6  8]
 [10 12]]
[[ 4  6]
 [12 14]]
[[ 3  7]
 [11 15]]


## Dimension Operation

We can use reshape to reshape the dimension of matrix.

We can use flatten to make a 1D array.

We can use stack fucntion to concatenate two matrices

In [ ]:
arr = np.arange(24)

arr_1 = arr.reshape(4, 6)  # shape: (4,6)
arr_2 = arr.reshape(2, 3, 4)  # shape: (2,3,4)

## This will reshape the array into 1D copy
flattened = arr_1.flatten()  # shape: (24,)
print("Flattened 1D Array:", flattened)

## This will reshape the array into 1D view
raveled = arr_2.ravel()  # shape: (24,)

## Dimensions manipulation
expanded = arr_1[:, :, np.newaxis]  # shape: (4,6,1)
print("Expanded Array Shape:", expanded.shape)
squeezed = expanded.squeeze()  # shape: (4,6)
print("Squeezed Array Shape:", squeezed.shape)

Flattened 1D Array: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
Expanded Array Shape: (4, 6, 1)
Squeezed Array Shape: (4, 6)


In [15]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[7, 8, 9], [10, 11, 12]])

vertical_stack = np.vstack((a, b))  # Stack arrays vertically
horizontal_stack = np.hstack((a, b))  # Stack arrays horizontally
print("Vertical Stack:\n", vertical_stack)
print("Horizontal Stack:\n", horizontal_stack)

depth_stack = np.dstack([a, b])          # Stack along third dimension
print("Depth Stack:\n", depth_stack)

Vertical Stack:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Horizontal Stack:
 [[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
Depth Stack:
 [[[ 1  7]
  [ 2  8]
  [ 3  9]]

 [[ 4 10]
  [ 5 11]
  [ 6 12]]]


In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[7, 8, 9], [10, 11, 12]])

# Using concatenate for more control
concat_axis0 = np.concatenate([a, b], axis=0)  # Along rows
concat_axis1 = np.concatenate([a, b], axis=1)  # Along columns
print("Concatenated along axis 0:\n", concat_axis0)
print("Concatenated along axis 1:\n", concat_axis1)

Concatenated along axis 0:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Concatenated along axis 1:
 [[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [26]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[7, 8, 9], [10, 11, 12]])
c = a + b

spilt_arrays_1 = np.array_split(c, 2, axis = 1)  # Split into 2 parts along columns
spilt_arrays_2 = np.array_split(c, 2, axis = 0)  # Split into 2 parts along rows
print("Split Arrays:", spilt_arrays_1)
print("Split Arrays:", spilt_arrays_2)

Split Arrays: [array([[ 8, 10],
       [14, 16]]), array([[12],
       [18]])]
Split Arrays: [array([[ 8, 10, 12]]), array([[14, 16, 18]])]
